import { Box, Input, Stack } from '@chakra-ui/react';
import { Header, Result, Tips } from '../components';
import { Head } from 'next/head';

export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>SPLLITER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/images/favicon-32x32.png" />
      </Head> */}
      <Box>
        <Header />
        <Stack display="flex" flexDirection="column" p="40px" spacing="70px">
          <Input label="Bill" />
          <Tips />
          <Input label="Number of People" />
          <Result />
        </Stack>
      </Box>
    </div>
  );
}
